spring.application.name=Biblioteca-Online

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

google.books.api.base-url=${GOOGLE_BOOKS_API_BASE_URL:https://www.googleapis.com}
google.books.api.key=${GOOGLE_BOOKS_API_KEY:}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=505MB
