events {}

http {
    server {
        listen 80;
        server_name biblioteca-online.localhost;

        location / {
            proxy_pass http://frontend:3000;
        }

        location /api {
            proxy_pass http://backend:8080;
        }

        location ^~ /api/biblioteca/livros/ {
            proxy_pass http://backend:8080;
            proxy_connect_timeout 30s;
            proxy_send_timeout 1800s;
            proxy_read_timeout 1800s;
            proxy_buffering off;
        }

        location = /api/acervo/livros/catalogo/cc-by-sa/gerar-pdfs {
            proxy_pass http://backend:8080;
            proxy_connect_timeout 30s;
            proxy_send_timeout 1800s;
            proxy_read_timeout 1800s;
        }
    }
}
